### ISSUE TITLE
Reloading the integration keeps old update instances

### ISSUE THREAD

**Issue by sfalkman** [sfalkman/ngenic-hass-platform#23]
When reloading the integration (Configuration -> Integrations -> Ngenic -> Reload) we start receiving errors like this:
```
2020-12-30 20:48:48 DEBUG (MainThread) [custom_components.ngenic.sensor] Fetch measurement (name=Ngenic sensor, type=MeasurementType.POWER_KW)
2020-12-30 20:48:48 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ngenicpy/models/base.py", line 172, in _async_request
    r = await request_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 1548, in get
    return await self.request(
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 1371, in request
    response = await self.send(
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 1399, in send
    raise RuntimeError("Cannot send a request, as the client has been closed.")
RuntimeError: Cannot send a request, as the client has been closed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/ngenic/sensor.py", line 254, in _async_update
    new_state = await self._async_fetch_measurement()
  File "/config/custom_components/ngenic/sensor.py", line 299, in _async_fetch_measurement
    current = await get_measurement_value(self._node, measurement_type=self._measurement_type)
  File "/config/custom_components/ngenic/sensor.py", line 90, in get_measurement_value
    measurement = await node.async_measurement(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/ngenicpy/models/node.py", line 151, in async_measurement
    return await self._async_parse_new_instance(url, Measurement, node=self, measurement_type=measurement_type)
  File "/usr/local/lib/python3.8/site-packages/ngenicpy/models/base.py", line 120, in _async_parse_new_instance
    ret_json = self._parse(await self._async_get(url))
  File "/usr/local/lib/python3.8/site-packages/ngenicpy/models/base.py", line 238, in _async_get
    return await self._async_request("get",
  File "/usr/local/lib/python3.8/site-packages/ngenicpy/models/base.py", line 181, in _async_request
    raise ClientException(self._get_error("An exception occurred", r, parent_ex=exc))
ngenicpy.exceptions.ClientException: (ClientException(...), 'An exception occurred: Cannot send a request, as the client has been closed.')
```

This is most likely because we're updating the sensors by adding each of them to an `async_track_time_interval` and these update-instances are not removed when the integration is reloaded. This leads to multiple updates of the same entity, but only the most recent will work (the other doesn't have any reference to a client anymore).

**Comment by sfalkman** [comment]
Fixed by #24
